#
# Chef Client Config File
#
# Dynamically generated by Chef - local modifications will be replaced
#
log_level          :warn
log_location       "/var/log/chef/client.log"
ssl_verify_mode    :verify_none
chef_server_url    "http://localhost:4000"

validation_client_name "chef-validator"
validation_key      	 "/etc/chef/validation.pem"
client_key          	 "/etc/chef/client.pem"

cache_options({ :path => "/var/cache/chef/client_checksums", :skip_expires => true})

signing_ca_user "chef"

file_cache_path    "/var/cache/chef/file_cache"
pid_file           "/var/run/chef/client.pid"

Mixlib::Log::Formatter.show_time = true

Ohai::Config[:plugin_path] << "/etc/ohai/plugins"

