#
# Chef Server Config File
#
# Dynamically generated by Chef - local modifications will be replaced

log_level          :warn
log_location       "/var/log/chef/server.log"
ssl_verify_mode    :verify_none
#
# hard set to localhost for noe
#
chef_server_url    "http://localhost:4000"

signing_ca_path    "/data/chef/ca"
couchdb_database   'chef'
couchdb_url "http://chef:#{File.read('/etc/chef/couchdb_pass')}@localhost:5984"

cookbook_path      [ "/data/chef/cookbooks", "/data/chef/site-cookbooks" ]

node_path          "/data/chef/nodes"
file_cache_path    "/data/chef/file-cache"
openid_store_path  "/data/chef/openid/store"
openid_cstore_path "/data/chef/openid/cstore"
search_index_path  "/data/chef/search_index"
role_path          "/data/chef/roles"

validation_client_name "chef-validator"
validation_key         "/etc/chef/server-validation.pem"
client_key             "/etc/chef/client.pem"
web_ui_client_name     "chef-webui"
web_ui_key             "/etc/chef/webui.pem"

web_ui_admin_user_name "admin"
web_ui_admin_default_password ""

supportdir = "/data/chef/support"
solr_jetty_path File.join(supportdir, "solr", "jetty")
solr_data_path  File.join(supportdir, "solr", "data")
solr_home_path  File.join(supportdir, "solr", "home")
solr_heap_size  "256M"

umask 18

cache_options({ :path => "/data/chef/cache", :skip_expires => true})
checksum_path "/data/chef/checksums"
sandbox_path "/data/chef/sandboxes"

signing_ca_cert "/etc/chef/certificates/cert.pem"
signing_ca_key "/etc/chef/certificates/key.pem"
signing_ca_user "chef"
signing_ca_group "chef"


amqp_pass File.read('/etc/chef/amqp_passwd').chomp

Mixlib::Log::Formatter.show_time = true
